name: 🎨 Theme Submission
description: Submit a custom Omarchy theme to be featured on the website
title: "[THEME] Your Theme Name"
labels: ["theme", "submission"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating a custom Omarchy theme! Please fill out the form below to submit your theme.

  - type: input
    id: theme-name
    attributes:
      label: Theme Name
      description: Give your theme a descriptive name
      placeholder: "e.g., Tokyo Night, Rose Pine, Custom Dark"
    validations:
      required: true

  - type: input
    id: theme-category
    attributes:
      label: Theme Category
      description: What type of theme is this?
      placeholder: "e.g., Dark Theme, Light Theme, High Contrast, Colorful, Minimal"
    validations:
      required: true


  - type: input
    id: author-name
    attributes:
      label: Author Name
      description: Your name or GitHub username
      placeholder: "Your Name or @username"
    validations:
      required: true

  - type: input
    id: theme-link
    attributes:
      label: Theme Repository/Download Link
      description: Link to your theme files (GitHub repo, download, etc.)
      placeholder: "https://github.com/username/omarchy-theme"
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated tags (e.g., official, popular, pastel, custom)
      placeholder: "custom, dark, purple, minimal"
    validations:
      required: true

  - type: input
    id: screenshot-url
    attributes:
      label: Screenshot URL (Optional)
      description: External URL to a high-quality screenshot showing your theme in action
      placeholder: "https://example.com/theme-screenshot.jpg"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Screenshot**: You can either upload a screenshot directly to this issue or provide an external URL above. Please provide a high-quality screenshot showing your theme in action.

  - type: checkboxes
    id: checklist
    attributes:
      label: Submission Checklist
      description: Please confirm the following
      options:
        - label: I have read the contribution guidelines
          required: true
        - label: My theme is compatible with Omarchy
          required: true
        - label: I will provide a screenshot showing the theme in action (either by upload or URL)
          required: true
        - label: I have permission to share this content
          required: true
